import type { Rule } from "../types/index.js";

/**
 * 默认评分规则集
 * 所有阈值集中配置，sourceType 明确标注
 */
export const DEFAULT_RULES: Rule[] = [
  // ===== 水力性能 — 25分 =====
  {
    id: "rule-tmp",
    name: "TMP绝对值",
    category: "水力性能",
    metric: "currentTMP",
    unit: "kPa",
    sourceType: "manual",
    sourceDescription: "产品说明书：推荐工作范围 10–30 kPa",
    warningThreshold: 30,
    alarmThreshold: 40,
    redlineThreshold: 50,
    scoreBands: [
      { min: 0, max: 30, scoreRatio: 1.0, label: "excellent" },
      { min: 30, max: 40, scoreRatio: 0.7, label: "good" },
      { min: 40, max: 50, scoreRatio: 0.4, label: "fair" },
      { min: 50, max: 999, scoreRatio: 0.0, label: "poor" },
    ],
    enabled: true,
    recommendation: "TMP偏高时检查膜污染程度，安排化学清洗。",
  },
  {
    id: "rule-flux-ratio",
    name: "通量达标率",
    category: "水力性能",
    metric: "fluxRatio",
    unit: "%",
    sourceType: "manual",
    sourceDescription: "产品说明书：推荐通量 10–25 L/(m²·h)",
    warningThreshold: 80,
    alarmThreshold: 60,
    redlineThreshold: 30,
    scoreBands: [
      { min: 90, max: 999, scoreRatio: 1.0, label: "excellent" },
      { min: 70, max: 90, scoreRatio: 0.7, label: "good" },
      { min: 50, max: 70, scoreRatio: 0.5, label: "fair" },
      { min: 0, max: 50, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "通量低于设计值时，检查膜污染状态或进水条件变化。",
  },
  {
    id: "rule-permeability-retention",
    name: "比通量保持率",
    category: "水力性能",
    metric: "permeabilityRetention",
    unit: "%",
    sourceType: "site-calibrated",
    sourceDescription: "与健康期基准比通量比值",
    warningThreshold: 70,
    alarmThreshold: 50,
    redlineThreshold: null,
    scoreBands: [
      { min: 85, max: 999, scoreRatio: 1.0, label: "excellent" },
      { min: 70, max: 85, scoreRatio: 0.8, label: "good" },
      { min: 50, max: 70, scoreRatio: 0.5, label: "fair" },
      { min: 0, max: 50, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "比通量持续下降说明膜污染加剧，需评估清洗策略。",
  },
  {
    id: "rule-tmp-increase",
    name: "TMP日增长率",
    category: "水力性能",
    metric: "tmpDailyIncrease",
    unit: "kPa/d",
    sourceType: "engineering",
    sourceDescription: "工程经验值",
    warningThreshold: 0.5,
    alarmThreshold: 1.0,
    redlineThreshold: null,
    scoreBands: [
      { min: -999, max: 0.3, scoreRatio: 1.0, label: "excellent" },
      { min: 0.3, max: 0.5, scoreRatio: 0.8, label: "good" },
      { min: 0.5, max: 1.0, scoreRatio: 0.5, label: "fair" },
      { min: 1.0, max: 999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "TMP快速增长表明污染速率加快，缩短清洗周期或调整运行参数。",
  },
  {
    id: "rule-flow-deviation",
    name: "膜箱间流量偏差",
    category: "水力性能",
    metric: "flowDeviation",
    unit: "%",
    sourceType: "engineering",
    sourceDescription: "工程经验值",
    warningThreshold: 15,
    alarmThreshold: 25,
    redlineThreshold: null,
    scoreBands: [
      { min: 0, max: 10, scoreRatio: 1.0, label: "excellent" },
      { min: 10, max: 20, scoreRatio: 0.7, label: "good" },
      { min: 20, max: 30, scoreRatio: 0.4, label: "fair" },
      { min: 30, max: 999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "流量偏差大表明个别膜箱污染不均匀或存在局部堵塞。",
  },

  // ===== 膜完整性及出水 — 25分 =====
  {
    id: "rule-turbidity",
    name: "产水浊度",
    category: "膜完整性及出水",
    metric: "turbidity",
    unit: "NTU",
    sourceType: "manual",
    sourceDescription: "产品说明书和饮用水标准",
    warningThreshold: 0.3,
    alarmThreshold: 0.5,
    redlineThreshold: 1.0,
    scoreBands: [
      { min: 0, max: 0.1, scoreRatio: 1.0, label: "excellent" },
      { min: 0.1, max: 0.3, scoreRatio: 0.8, label: "good" },
      { min: 0.3, max: 0.5, scoreRatio: 0.5, label: "fair" },
      { min: 0.5, max: 999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "浊度偏高应首先排除膜完整性问题和仪表故障。",
  },
  {
    id: "rule-ss",
    name: "产水SS",
    category: "膜完整性及出水",
    metric: "ss",
    unit: "mg/L",
    sourceType: "engineering",
    sourceDescription: "工程经验值",
    warningThreshold: 2,
    alarmThreshold: 5,
    redlineThreshold: null,
    scoreBands: [
      { min: 0, max: 1, scoreRatio: 1.0, label: "excellent" },
      { min: 1, max: 3, scoreRatio: 0.7, label: "good" },
      { min: 3, max: 5, scoreRatio: 0.4, label: "fair" },
      { min: 5, max: 999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "SS偏高结合浊度综合判断膜完整性。",
  },
  {
    id: "rule-airtight",
    name: "气密试验",
    category: "膜完整性及出水",
    metric: "airTightTestPassed",
    unit: "—",
    sourceType: "manual",
    sourceDescription: "产品说明书：0.02 MPa 无泄漏",
    warningThreshold: null,
    alarmThreshold: null,
    redlineThreshold: null,
    scoreBands: [],
    enabled: true,
    recommendation: "气密试验不合格需立即定位泄漏点。",
  },
  {
    id: "rule-fiber-break-rate",
    name: "膜丝封堵情况",
    category: "膜完整性及出水",
    metric: "fiberBlockageLevel",
    unit: "等级",
    sourceType: "engineering",
    sourceDescription: "现场检测定性分级：未发现、轻微、中度、严重",
    warningThreshold: null,
    alarmThreshold: null,
    redlineThreshold: null,
    scoreBands: [],
    enabled: true,
    recommendation: "中度封堵应安排检查处理，严重封堵应尽快停机排查并评估更换。",
  },

  // ===== 污染与清洗恢复 — 20分 =====
  {
    id: "rule-cip-recovery",
    name: "在线清洗恢复率",
    category: "污染与清洗恢复",
    metric: "cipRecoveryRate",
    unit: "%",
    sourceType: "site-calibrated",
    sourceDescription: "在线清洗后比通量 / 基准比通量",
    warningThreshold: 80,
    alarmThreshold: 60,
    redlineThreshold: null,
    scoreBands: [
      { min: 90, max: 999, scoreRatio: 1.0, label: "excellent" },
      { min: 75, max: 90, scoreRatio: 0.7, label: "good" },
      { min: 55, max: 75, scoreRatio: 0.4, label: "fair" },
      { min: 0, max: 55, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "在线清洗恢复率低说明不可逆污染比例较高，需评估离线清洗。",
  },
  {
    id: "rule-irreversible-index",
    name: "不可逆污染指数",
    category: "污染与清洗恢复",
    metric: "irreversibleFoulingIndex",
    unit: "—",
    sourceType: "engineering",
    sourceDescription: "1 - 清洗后比通量 / 基准比通量",
    warningThreshold: 0.3,
    alarmThreshold: 0.5,
    redlineThreshold: null,
    scoreBands: [
      { min: 0, max: 0.2, scoreRatio: 1.0, label: "excellent" },
      { min: 0.2, max: 0.35, scoreRatio: 0.7, label: "good" },
      { min: 0.35, max: 0.5, scoreRatio: 0.4, label: "fair" },
      { min: 0.5, max: 1, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "不可逆污染指数≥0.5说明膜已严重老化或污染，需评估更换。",
  },
  {
    id: "rule-cleaning-cycle",
    name: "清洗周期偏离",
    category: "污染与清洗恢复",
    metric: "cleaningCycleDeviation",
    unit: "%",
    sourceType: "site-calibrated",
    sourceDescription: "当前清洗周期 / 历史正常清洗周期的偏离",
    warningThreshold: 50,
    alarmThreshold: 70,
    redlineThreshold: null,
    scoreBands: [
      { min: -999, max: 30, scoreRatio: 1.0, label: "excellent" },
      { min: 30, max: 50, scoreRatio: 0.7, label: "good" },
      { min: 50, max: 70, scoreRatio: 0.4, label: "fair" },
      { min: 70, max: 999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "清洗周期明显缩短说明污染速度加快。",
  },
  {
    id: "rule-tmp-rebound",
    name: "TMP反弹速度",
    category: "污染与清洗恢复",
    metric: "tmpReboundSpeed",
    unit: "—",
    sourceType: "engineering",
    sourceDescription: "清洗后TMP恢复到清洗前水平的速度",
    warningThreshold: null,
    alarmThreshold: null,
    redlineThreshold: null,
    scoreBands: [],
    enabled: true,
    recommendation: "反弹快说明存在快速污染因素，需排查进水水质或运行参数。",
  },
  {
    id: "rule-fouling-severity",
    name: "污染综合程度",
    category: "污染与清洗恢复",
    metric: "foulingComposite",
    unit: "—",
    sourceType: "engineering",
    sourceDescription: "滤饼+有机+无机+生物+毛发的综合评估",
    warningThreshold: null,
    alarmThreshold: null,
    redlineThreshold: null,
    scoreBands: [],
    enabled: true,
    recommendation: "多种污染并存时需制定综合清洗方案。",
  },

  // ===== 机械及组件状态 — 15分（12项各占1.25分，由引擎统一处理） =====
  {
    id: "rule-mechanical",
    name: "机械及组件状态综合",
    category: "机械及组件状态",
    metric: "mechanicalStatus",
    unit: "—",
    sourceType: "engineering",
    sourceDescription: "12项机械状态检查",
    warningThreshold: null,
    alarmThreshold: null,
    redlineThreshold: null,
    scoreBands: [],
    enabled: true,
    recommendation: "任何damaged项应立即安排维修。",
  },

  // ===== 运行风险暴露 — 10分 =====
  {
    id: "rule-risk-events",
    name: "风险事件次数",
    category: "运行风险暴露",
    metric: "riskEventCount",
    unit: "次",
    sourceType: "engineering",
    sourceDescription: "8类风险事件的触发数量",
    warningThreshold: 1,
    alarmThreshold: 3,
    redlineThreshold: null,
    scoreBands: [
      { min: 0, max: 0, scoreRatio: 1.0, label: "excellent" },
      { min: 1, max: 2, scoreRatio: 0.6, label: "good" },
      { min: 2, max: 4, scoreRatio: 0.3, label: "fair" },
      { min: 4, max: 999, scoreRatio: 0.0, label: "poor" },
    ],
    enabled: true,
    recommendation: "风险事件频繁说明运行管理存在系统性问题。",
  },
  {
    id: "rule-mlss",
    name: "MLSS",
    category: "运行风险暴露",
    metric: "mlss",
    unit: "mg/L",
    sourceType: "manual",
    sourceDescription: "产品说明书：推荐 3000–8000 mg/L，最大 10000 mg/L",
    warningThreshold: 8000,
    alarmThreshold: 10000,
    redlineThreshold: null,
    scoreBands: [
      { min: 3000, max: 8000, scoreRatio: 1.0, label: "excellent" },
      { min: 2000, max: 3000, scoreRatio: 0.7, label: "good" },
      { min: 8000, max: 10000, scoreRatio: 0.7, label: "good" },
      { min: 0, max: 2000, scoreRatio: 0.3, label: "fair" },
      { min: 10000, max: 99999, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "MLSS过高会加速膜污染，过低影响处理效果，需调整排泥策略。",
  },

  // ===== 维护与数据可靠性 — 5分 =====
  {
    id: "rule-data-completeness",
    name: "数据完整度",
    category: "维护与数据可靠性",
    metric: "dataCompleteness",
    unit: "%",
    sourceType: "engineering",
    sourceDescription: "必填字段的填写率",
    warningThreshold: 85,
    alarmThreshold: 70,
    redlineThreshold: null,
    scoreBands: [
      { min: 95, max: 100, scoreRatio: 1.0, label: "excellent" },
      { min: 85, max: 95, scoreRatio: 0.8, label: "good" },
      { min: 70, max: 85, scoreRatio: 0.5, label: "fair" },
      { min: 0, max: 70, scoreRatio: 0.1, label: "poor" },
    ],
    enabled: true,
    recommendation: "数据不完整会影响评估准确性，请补充缺失的检测项目。",
  },
];
